### PR TITLE
Added generic overload of makeRelationship method

### PR DESCRIPTION
**Pull request by xapfrom**
Hi. Hope I'm not violating any of your rules but would love it if you could take a look at my PR.  The method I added lets you call makeRelationship in a generic way, loosely coupled from any concrete types. It has proved quite handy on other projects.  Thanks.

-Xavier

### CODE REVIEW

**Comment by afawcett** [comment]
Thanks @xapfrom i can see how this would be useful. My main tip is to delegate to the type safe version from the untyped version so there is not to implementations of the methods. Make sense?

**Comment by xapfrom** [comment]
Ugh, yes. Looking at it again there's way too much in common between the
two methods. I'll get it sorted. Thanks.

**Comment by xapfrom** [comment]
@afawcett Simply calling the original makeRelationship from the generic version resulted in a null reference error on line 71. However, I factored out the common functionality into a new method, deserializeParentsAndChildren. All tests continue to pass. Does that work?  Happy to make any further changes.  Thanks.

**Comment by afawcett** [comment]
Thanks @xapfrom . This looks better for sure. I would like to see getField more robust though. Can you put in some defensive coding for bad object name for example.

**Comment by dbtavernerffdc** [comment]
@xapfrom all merged. Thank you very much for the submission.

**Pull request merged**
