### PR TITLE
Feature/stub api

### PR DESCRIPTION
**Pull request by frup42**
Do not commit before Spring 17!!

### CODE REVIEW

**Comment by frup42** [comment]
#26

**Comment by afawcett** [comment]
Very cool! 👍

**Comment by arangari** [comment]
@frup42,  Is this planned to be included soon?

**Comment by frup42** [comment]
@arangari This will fail to compile in pre-Spring 17 orgs, so I'm holding off merging until Jan 22 when the release is rolled out to the majority of orgs.

**Comment by afawcett** [comment]
@frup42 time to merge!?!? 👍

**Comment by frup42** [comment]
Not time to merge.. I want to change the method signature from factory to mock, to match Mockito syntax. Will make the changes today.

**Comment by capeterson** [comment]
@frup42 can I confirm that once this is merged the mocks generator JAR will no longer be needed to make use of apexmocks?

**Comment by frup42** [comment]
@capeterson We want to keep the generator for the foreseeable future.
Rather than forcing everyone to switch their tests immediately, I'd like to keep the backwards compatibility.
Also, generating the mocks is the only viable workaround for some major stub API gaps - namely the inability to mock inner classes and abstract classes.

But yes, the generator will become optional when using apexmocks, reducing the barrier to adoption :)

**Pull request merged**
